version: '3.8'

services:
  flixhub-api:
    build:
      context: .
      dockerfile: Application/Services/FlixHub.Api/Dockerfile
    container_name: flixhub-api
    ports:
      - "2535:8080"
      - "6979:8081"
    env_file:
      - .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    dns:
      - 8.8.8.8
      - 8.8.4.4
    restart: unless-stopped
    networks:
      - flixhub-network

networks:
  flixhub-network:
    driver: bridge
