version: '3.8'

name: flixhub-api  # Optional: sets project name explicitly

services:
  flixhub-api:
    build:
      context: .
      dockerfile: Application/Services/FlixHub.Api/Dockerfile
    image: flixhub:latest
    container_name: flixhub-api
    ports:
      - "2535:8080"
      - "6979:8081"
    env_file:
      - .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    restart: unless-stopped
