name: flixhub-api  # Optional: sets project name explicitly

services:
  flixhub-api:
    build:
      context: .
      dockerfile: Application/Services/FlixHub.Api/Dockerfile
    image: flixhub:latest
    container_name: flixhub-api
    ports:
      - "2535:8080"
      - "6979:8081"
    volumes:
      - ./logs:/app/logs  # Mount host logs directory to container
    env_file:
      - .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ElasticSearch__FolderPath=/app/logs  # Override the folder path for Docker
    restart: unless-stopped
