services:
  sonarqube:
    image: sonarqube:25.10.0.114319-community
    container_name: sonarqube
    ports:
      - "9000:9000"
    volumes:
      - sq_data:/opt/sonarqube/data
      - sq_extensions:/opt/sonarqube/extensions
      - sq_logs:/opt/sonarqube/logs
    networks:
      - sonarqube_net

volumes:
  sq_data:
  sq_extensions:
  sq_logs:

networks:
  sonarqube_net:
    name: sonarqube-net
    driver: bridge