services:
  sonarqube:
    image: sonarqube:25.10.0.114319-community
    container_name: sonarqube
    networks:
      - flixhub-net
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://postgres-dev:5432/sonarqube
      SONAR_JDBC_USERNAME: sonarqube
      SONAR_JDBC_PASSWORD: sa
    ports:
      - "9000:9000"
    volumes:
      - sonar_data:/opt/sonarqube/data
      - sonar_extensions:/opt/sonarqube/extensions
      - sonar_logs:/opt/sonarqube/logs

networks:
  flixhub-net:
    external: true

volumes:
  sonar_data:
  sonar_extensions:
  sonar_logs:
